# Generated by Django 5.2.4 on 2025-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('school', models.CharField(choices=[('sorcery', 'Sorcery'), ('pyromancy', 'Pyromancy'), ('miracle', 'Miracle'), ('hex', 'Hex')], max_length=20)),
                ('slots_required', models.IntegerField(default=1)),
                ('uses', models.IntegerField(default=1)),
                ('cost_fp', models.IntegerField(default=0, verbose_name='Focus Points Cost')),
                ('cost_stamina', models.IntegerField(default=0)),
                ('intelligence_required', models.IntegerField(default=0)),
                ('faith_required', models.IntegerField(default=0)),
                ('is_offensive', models.BooleanField(default=True)),
                ('is_buff', models.BooleanField(default=False)),
                ('is_heal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='weapons/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('sword', 'Sword'), ('axe', 'Axe'), ('bow', 'Bow'), ('spear', 'Spear'), ('greatsword', 'Greatsword'), ('katana', 'Katana'), ('fist', 'Fist'), ('halberd', 'Halberd'), ('magic', 'Magic')], max_length=20)),
                ('physical_damage', models.IntegerField(default=0)),
                ('magic_damage', models.IntegerField(default=0)),
                ('fire_damage', models.IntegerField(default=0)),
                ('lightning_damage', models.IntegerField(default=0)),
                ('critical', models.IntegerField(default=100)),
                ('durability', models.IntegerField(default=100)),
                ('weight', models.FloatField()),
                ('strength_required', models.IntegerField()),
                ('dexterity_required', models.IntegerField()),
                ('intelligence_required', models.IntegerField()),
                ('faith_required', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
