# Generated by Django 5.2.4 on 2025-07-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artorias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='cost_stamina',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='is_buff',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='is_heal',
        ),
        migrations.AlterField(
            model_name='spell',
            name='cost_fp',
            field=models.IntegerField(default=10, verbose_name='Focus Points Cost'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='intelligence_required',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='dexterity_required',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='faith_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='intelligence_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='strength_required',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
